"use client";

import { LucideShieldAlert, LucideShieldCheck, LucideShieldEllipsis, LucideInfo, LucideTerminal, LucideCheckCircle2, LucideAlertTriangle, Copy, Check } from "lucide-react";
import { useState } from "react";

interface SecurityData {
  risk_level: 'LOW' | 'MEDIUM' | 'HIGH';
  supports_scoping: boolean;
  what_it_does: string;
  what_it_accesses: string[];
  worst_case_scenario: string;
  recommendation: string;
  safe_install_command?: string;
  unsafe_install_command?: string;
  scope_guide: string;
  signals?: { type: 'TRUST' | 'RISK', message: string }[];
}

export function SecurityGuide({ data, serverName }: { data: SecurityData | null, serverName: string }) {
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied_safe' | 'copied_unsafe'>('idle');

  if (!data) {
    return (
      <div className="space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="p-16 rounded-[4rem] bg-[#070707] border border-zinc-900 overflow-hidden relative group">
           {/* Background branding */}
           <div className="absolute -top-24 -right-24 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl group-hover:bg-emerald-500/10 transition-colors duration-1000" />
           
           <div className="relative z-10 space-y-12">
              <div className="flex items-center gap-6">
                 <div className="w-16 h-16 rounded-3xl bg-zinc-900 border border-zinc-800 flex items-center justify-center shadow-2xl">
                    <LucideShieldCheck className="w-8 h-8 text-emerald-500" />
                 </div>
                 <div>
                    <h2 className="text-3xl font-black text-white tracking-tight leading-none">MCPHub Trust Score Logic</h2>
                    <p className="text-xs font-black text-zinc-600 uppercase tracking-[0.3em] mt-3">Registry Reliability Index v1.0</p>
                 </div>
              </div>

              <p className="text-lg text-zinc-400 font-medium leading-relaxed max-w-3xl">
                 The **Trust Score** is a dynamic, multi-layered metric (1.0 - 10.0) generated by the MCPHub Discovery Engine. It serves as a real-time health and security check for every server in the registry.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-10 pt-12 border-t border-zinc-900">
                 {/* Pillar 1 */}
                 <div className="space-y-4">
                    <div className="flex items-center gap-3">
                       <LucideCheckCircle2 className="w-4 h-4 text-emerald-500" />
                       <h4 className="text-sm font-black text-white uppercase tracking-widest">1. Repository Reputation (35%)</h4>
                    </div>
                    <ul className="text-xs text-zinc-600 font-bold space-y-2 pl-7 list-disc">
                       <li>**Star Count**: Community validation through GitHub stars.</li>
                       <li>**Longevity**: How long the repository has been active.</li>
                       <li>**Contributor Base**: Diversity and reputation of the developers involved.</li>
                    </ul>
                 </div>
                 {/* Pillar 2 */}
                 <div className="space-y-4">
                    <div className="flex items-center gap-3">
                       <LucideCheckCircle2 className="w-4 h-4 text-emerald-500" />
                       <h4 className="text-sm font-black text-white uppercase tracking-widest">2. Operational Health (25%)</h4>
                    </div>
                    <ul className="text-xs text-zinc-600 font-bold space-y-2 pl-7 list-disc">
                       <li>**Update Frequency**: How recently the code was modified.</li>
                       <li>**Issue Resolution**: Speed and transparency in handling community bugs.</li>
                       <li>**Maintenance Status**: Detection of archived or abandoned states.</li>
                    </ul>
                 </div>
                 {/* Pillar 3 */}
                 <div className="space-y-4">
                    <div className="flex items-center gap-3">
                       <LucideCheckCircle2 className="w-4 h-4 text-emerald-500" />
                       <h4 className="text-sm font-black text-white uppercase tracking-widest">3. AI Security Scan (30%)</h4>
                    </div>
                    <ul className="text-xs text-zinc-600 font-bold space-y-2 pl-7 list-disc">
                       <li>**Permission Scoping**: Analysis of requested capabilities.</li>
                       <li>**Pattern Matching**: Automated detection of risky code (eval, shell exec).</li>
                       <li>**Dependency Audit**: Checking for known vulnerabilities in sub-packages.</li>
                    </ul>
                 </div>
                 {/* Pillar 4 */}
                 <div className="space-y-4">
                    <div className="flex items-center gap-3">
                       <LucideCheckCircle2 className="w-4 h-4 text-emerald-500" />
                       <h4 className="text-sm font-black text-white uppercase tracking-widest">4. Metadata (10%)</h4>
                    </div>
                    <ul className="text-xs text-zinc-600 font-bold space-y-2 pl-7 list-disc">
                       <li>**README Quality**: Presence of clear installation guides.</li>
                       <li>**Community Feedback**: Verification statuses within the ecosystem.</li>
                    </ul>
                 </div>
              </div>

              {/* Scoring Tiers Table */}
              <div className="pt-12 border-t border-zinc-900">
                 <h4 className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.4em] mb-8">Scoring Tiers & Classifications</h4>
                 <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {[
                       { range: "8.5 - 10.0", tier: "💎 Elite", desc: "Secure, highly active, and widely trusted." },
                       { range: "7.0 - 8.4", tier: "✅ Verified", desc: "Safe for general use; maintained strategy." },
                       { range: "5.0 - 6.9", tier: "⚠️ Stable", desc: "Functional but limited documentation." },
                       { range: "Below 5.0", tier: "🔍 Experimental", desc: "Use with caution; unmaintained status." }
                    ].map((tier, i) => (
                       <div key={i} className="p-6 rounded-3xl bg-[#090909] border border-zinc-900 group-hover:border-zinc-800 transition-colors">
                          <p className="text-emerald-500 font-black text-xs mb-2 tracking-tighter">{tier.range}</p>
                          <p className="text-white font-black text-[10px] uppercase tracking-widest mb-3">{tier.tier}</p>
                          <p className="text-[10px] text-zinc-600 font-bold leading-relaxed">{tier.desc}</p>
                       </div>
                    ))}
                 </div>
              </div>

              <div className="pt-8">
                 <div className="inline-flex items-center gap-4 px-8 py-4 bg-emerald-500/5 border border-emerald-500/10 rounded-full group/tip">
                    <div className="w-8 h-8 rounded-full bg-emerald-500/10 flex items-center justify-center">
                       <LucideInfo className="w-3.5 h-3.5 text-emerald-500" />
                    </div>
                    <p className="text-[10px] text-emerald-500/80 font-bold leading-relaxed">
                       **Transparency First**: The Trust Score is automated and neutral. Improvements in security practices update the score automatically in the next scan cycle.
                    </p>
                 </div>
              </div>
           </div>
        </div>
      </div>
    );
  }

  const riskColors = {
    LOW: "text-emerald-500 bg-emerald-500/5 border-emerald-500/10",
    MEDIUM: "text-amber-500 bg-amber-500/5 border-amber-500/10",
    HIGH: "text-rose-500 bg-rose-500/5 border-rose-500/10"
  };

  const copyToClipboard = (text: string, type: 'safe' | 'unsafe') => {
    navigator.clipboard.writeText(text);
    setCopyStatus(type === 'safe' ? 'copied_safe' : 'copied_unsafe');
    setTimeout(() => setCopyStatus('idle'), 2000);
  };

  return (
    <div className="space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Risk Summary Header - Minimalist */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-8 p-10 rounded-[3rem] bg-zinc-900/20 border border-zinc-900/50">
        <div className="flex items-center gap-8">
           <div className={`p-6 rounded-[2rem] border transition-all duration-700 ${riskColors[data.risk_level]}`}>
             {data.risk_level === 'LOW' ? <LucideShieldCheck className="w-8 h-8" /> : 
              data.risk_level === 'MEDIUM' ? <LucideShieldEllipsis className="w-8 h-8" /> : 
              <LucideShieldAlert className="w-8 h-8" />}
           </div>
           <div>
             <div className="flex items-center gap-3 mb-2">
                <span className={`text-[9px] font-black px-3 py-1 rounded-full uppercase tracking-[0.2em] ${riskColors[data.risk_level]}`}>
                   {data.risk_level} Risk Level
                </span>
                <span className="text-[9px] text-zinc-700 font-black uppercase tracking-widest">• Verified Registry Audit</span>
             </div>
             <h2 className="text-2xl font-black text-white tracking-tight leading-none">{serverName.replace(/-/g, ' ')} Safety Analysis</h2>
           </div>
        </div>
        
        <div className={`px-6 py-3 rounded-2xl font-black uppercase tracking-widest text-[9px] border ${data.supports_scoping ? 'bg-emerald-500/5 text-emerald-500 border-emerald-500/20 shadow-[0_0_15px_rgba(16,185,129,0.1)]' : 'bg-black text-zinc-600 border-zinc-900'}`}>
           {data.supports_scoping ? "Adjustable Scope Supported" : "Fixed Scope Policy"}
        </div>
      </div>

      {/* Trust & Risk Signals - NEW REASONING SYSTEM */}
      {data.signals && data.signals.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
           {data.signals.filter(s => s.type === 'TRUST').length > 0 && (
             <div className="p-8 rounded-[2.5rem] bg-emerald-500/[0.02] border border-emerald-500/10 space-y-4">
                <h3 className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.3em] flex items-center gap-2">
                   <LucideShieldCheck className="w-3.5 h-3.5" /> Trust Signals
                </h3>
                <div className="space-y-2">
                   {data.signals.filter(s => s.type === 'TRUST').map((s, i) => (
                      <div key={i} className="flex items-center gap-3 text-zinc-400 text-sm font-bold">
                         <div className="w-1 h-1 rounded-full bg-emerald-500 flex-shrink-0" />
                         {s.message}
                      </div>
                   ))}
                </div>
             </div>
           )}
           {data.signals.filter(s => s.type === 'RISK').length > 0 && (
             <div className="p-8 rounded-[2.5rem] bg-rose-500/[0.02] border border-rose-500/10 space-y-4">
                <h3 className="text-[10px] font-black text-rose-500 uppercase tracking-[0.3em] flex items-center gap-2">
                   <LucideAlertTriangle className="w-3.5 h-3.5" /> Risk Signals
                </h3>
                <div className="space-y-2">
                   {data.signals.filter(s => s.type === 'RISK').map((s, i) => (
                      <div key={i} className="flex items-center gap-3 text-zinc-400 text-sm font-bold">
                         <div className="w-1 h-1 rounded-full bg-rose-500 flex-shrink-0" />
                         {s.message}
                      </div>
                   ))}
                </div>
             </div>
           )}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        {/* Risk Breakdown */}
        <section className="space-y-8">
           <div className="space-y-3">
              <h3 className="text-[10px] font-black text-zinc-600 uppercase tracking-[0.3em] flex items-center gap-2">
                 <LucideShieldAlert className="w-3.5 h-3.5" /> Sensitive Access
              </h3>
              <div className="grid grid-cols-1 gap-2">
                 {data.what_it_accesses.map((item, i) => (
                   <div key={i} className="flex items-center gap-4 p-5 rounded-2xl bg-[#090909] border border-zinc-900 text-zinc-400 font-bold text-sm hover:border-zinc-800 transition-all">
                      <div className="w-1 h-1 rounded-full bg-rose-500 flex-shrink-0" />
                      {item}
                   </div>
                 ))}
              </div>
           </div>

           <div className="p-8 rounded-[2rem] bg-rose-500/[0.02] border border-rose-500/10 space-y-4">
              <h3 className="text-[10px] font-black text-rose-500 uppercase tracking-[0.3em] flex items-center gap-2">
                 <LucideAlertTriangle className="w-3.5 h-3.5" /> Worst Case scenario
              </h3>
              <p className="text-zinc-500 font-bold leading-relaxed text-base italic">
                 "{data.worst_case_scenario}"
              </p>
           </div>
        </section>

        {/* Actionable Recommendation */}
        <section className="space-y-8">
           <div className="p-10 rounded-[2.5rem] bg-[#090909] border border-zinc-900 space-y-6 flex flex-col justify-center h-full">
              <h3 className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.3em] flex items-center gap-2">
                 <LucideCheckCircle2 className="w-3.5 h-3.5" /> Security Recommendation
              </h3>
              <p className="text-lg text-zinc-300 font-black leading-snug">{data.recommendation}</p>
              <div className="pt-4 flex gap-4">
                 <div className="px-4 py-2 bg-emerald-500/5 rounded-full border border-emerald-500/10 text-[9px] font-black text-emerald-500/70 uppercase tracking-widest">Environment Isolation</div>
                 <div className="px-4 py-2 bg-zinc-800/10 rounded-full border border-zinc-900 text-[9px] font-black text-zinc-600 uppercase tracking-widest">Read-Only</div>
              </div>
           </div>
        </section>
      </div>

      {/* Installation Policy - Modern & Clean */}
      <section className="space-y-10 pt-10 border-t border-zinc-900">
         <div className="space-y-2">
            <h3 className="text-xl font-black text-white tracking-tight">Installation Policy</h3>
            <p className="text-sm text-zinc-600 font-bold uppercase tracking-widest">Choose the recommended strategy based on your environment</p>
         </div>

         <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            {/* Scoped Installation */}
            <div className="space-y-6">
               <div className="flex items-center justify-between px-2">
                  <h4 className="flex items-center gap-2.5 text-zinc-300 font-black text-sm uppercase tracking-widest">
                     <LucideShieldCheck className="w-4 h-4 text-emerald-500" /> Scoped Installation
                  </h4>
                  <span className="text-[9px] font-black text-emerald-500 uppercase bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/20">Recommended</span>
               </div>
               
               <div className="relative group overflow-hidden rounded-[2.5rem] border border-zinc-800 bg-[#070707] transition-all hover:border-zinc-700">
                  <div className="flex items-center justify-between px-8 py-5 bg-zinc-900/30 border-b border-zinc-800/50">
                     <LucideTerminal className="w-3.5 h-3.5 text-zinc-600" />
                     <button 
                       onClick={() => copyToClipboard(data.safe_install_command || "", 'safe')}
                       className="text-[9px] font-black uppercase text-zinc-500 hover:text-emerald-500 transition-all active:scale-95 flex items-center gap-2"
                     >
                       {copyStatus === 'copied_safe' ? <><Check className="w-3 h-3" /> Copied</> : <><Copy className="w-3 h-3" /> [Copy]</>}
                     </button>
                  </div>
                  <pre className="p-10 font-mono text-xs text-emerald-400 overflow-x-auto selection:bg-emerald-500/20">
                     {data.safe_install_command || `npx @modelcontextprotocol/${serverName} --scope restricted`}
                  </pre>
               </div>
               <p className="text-[11px] text-zinc-600 font-bold px-4">Minimal required permissions strategy. Highly recommended for sensitive workflows.</p>
            </div>

            {/* Unrestricted Access */}
            <div className="space-y-6">
               <div className="flex items-center justify-between px-2">
                  <h4 className="flex items-center gap-2.5 text-rose-500 font-black text-sm uppercase tracking-widest">
                     <LucideShieldAlert className="w-4 h-4" /> Unrestricted Access
                  </h4>
                  <span className="text-[9px] font-black text-rose-600 uppercase bg-rose-500/10 px-3 py-1 rounded-full border border-rose-500/20">High Risk Default</span>
               </div>
               
               <div className="relative group overflow-hidden rounded-[2.5rem] border border-rose-900/20 bg-rose-950/[0.02] transition-all hover:border-rose-900/40">
                  <div className="flex items-center justify-between px-8 py-5 bg-rose-950/10 border-b border-rose-900/20">
                     <LucideTerminal className="w-3.5 h-3.5 text-rose-900/50" />
                     <button 
                       onClick={() => copyToClipboard(data.unsafe_install_command || "", 'unsafe')}
                       className="text-[9px] font-black uppercase text-rose-800 hover:text-rose-500 transition-all active:scale-95 flex items-center gap-2"
                     >
                       {copyStatus === 'copied_unsafe' ? <><Check className="w-3 h-3" /> Copied</> : <><Copy className="w-3 h-3" /> [Copy]</>}
                     </button>
                  </div>
                  <pre className="p-10 font-mono text-xs text-rose-500 overflow-x-auto selection:bg-rose-500/20 font-black">
                     {data.unsafe_install_command || `npx @modelcontextprotocol/${serverName}`}
                  </pre>
               </div>
               <p className="text-[11px] text-zinc-700 font-bold px-4">Grants global access to the model. Use only in isolated environments.</p>
            </div>
         </div>
      </section>
    </div>
  );
}
